jobs:
  - job: build_and_publish
    displayName: build and publish artifacts
    variables:
      buildConfiguration: "Release"

    steps:
      - script: |
          echo $(ls)
          echo $(pwd)
          echo $(System.DefaultWorkingDirectory)
      - script: dotnet publish --configuration $(buildConfiguration) --output publish_output
        displayName: "dotnet build $(buildConfiguration)"

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "drop"
          publishLocation: "Container"
