parameters:
  - name: env
    type: string
  - name: azureSubscription
    type: string
  - name: resourceGroupName
    type: string
  - name: appName
    type: string

jobs:
  - deployment: functionAppDeployments
    displayName: deploy artifacts
    pool:
      workspace:
        clean: all
    environment: ${{parameters.env}}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - download: current
              displayName: Downloading the artifact from drop
            - task: AzureFunctionApp@1
              displayName: deploying the artifacts to ${{parameters.appName}}
              inputs:
                azureSubscription: ${{parameters.azureSubscription}}
                appType: "functionApp"
                appName: ${{parameters.appName}}
                package: $(Pipeline.Workspace)/**/*.zip
                deploymentMethod: "auto"
            - task: AzurePowerShell@5
              displayName: Updating AppSetting to ${{parameters.appName}}
              inputs:
                azureSubscription: ${{parameters.azureSubscription}}
                ScriptType: "InlineScript"
                Inline: |
                  # You can write your azure powershell scripts inline here. 
                  # You can also pass predefined and custom variables to this script using arguments

                  Update-AzFunctionAppSetting -Name ${{parameters.appName}} -ResourceGroupName ${{parameters.resourceGroupName}} -AppSetting @{"CUSTOM_FUNCTION_APP_SETTING" = "12345"}

                azurePowerShellVersion: "LatestVersion"
